kind: pipeline
name: default

steps:

  - name: build
    image: golang:alpine
    environment:
      CGO_ENABLED: 0
      GOPROXY: https://proxy.golang.org
    commands:
      - go build -o ormon-linux-amd64 ./cmd/ormon

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - ormon-linux-amd64
      checksum:
        - md5
        - sha1
        - sha256
    when:
      event: tag
