apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: bb-ormon-ext
rules:
- apiGroups:
  - route.openshift.io
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
